"""The README figure is generated by an example, and the example must keep working."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import numpy as np
import pytest

from conftest import DATA_DIR, ROOT

EXAMPLE = ROOT / "examples" / "plot_transform.py"
FIGURE = ROOT / "doc" / "how_it_works.png"
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"


def _load_example() -> ModuleType:
    pytest.importorskip("matplotlib")
    if not EXAMPLE.exists():  # pragma: no cover - a distribution without examples
        pytest.skip(f"example missing: {EXAMPLE}")
    spec = importlib.util.spec_from_file_location("plot_transform", EXAMPLE)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_the_figure_renders_from_the_sample(tmp_path: Path) -> None:
    example = _load_example()
    source = DATA_DIR / "earth.ppm"
    if not source.exists():  # pragma: no cover - the sdist ships no samples
        pytest.skip("sample image missing")
    output = example.main(tmp_path / "figure.png", source)
    data = output.read_bytes()
    assert data[:8] == PNG_MAGIC
    assert len(data) > 50_000, "a blank or broken figure is far smaller"


def test_the_block_shown_is_one_the_kept_corner_represents_well() -> None:
    """The figure's claim is checked, not just drawn: the chosen block keeps at
    least the promised share of its energy in the 16 coefficients, and the
    choice is deterministic so the figure is reproducible."""
    example = _load_example()
    source = DATA_DIR / "earth.ppm"
    if not source.exists():  # pragma: no cover - the sdist ships no samples
        pytest.skip("sample image missing")
    plane = example.luma_plane(source)
    top, left = example.pick_block(plane)
    assert (top, left) == example.pick_block(plane)
    assert top % 8 == 0 and left % 8 == 0

    block = plane[top : top + 8, left : left + 8]
    spectrum = example.WalshHadamardTransform().transform(block)
    share = float((spectrum[:4, :4] ** 2).sum() / (spectrum**2).sum())
    assert share >= example.ENERGY_SHARE_AT_LEAST
    assert block.std() > 20, "a flat block would satisfy the share trivially"


def test_pick_block_prefers_contrast_among_well_kept_blocks() -> None:
    example = _load_example()
    rng = np.random.default_rng(seed=53)
    plane = np.full((16, 16), 100.0)
    plane[:8, :8] += rng.uniform(-60, 60, size=(8, 8))  # texture: poorly kept
    plane[8:, 8:12], plane[8:, 12:] = 30.0, 220.0  # a step edge: well kept, high contrast
    plane[:8, 8:] = np.linspace(100, 120, 8)[None, :]  # a faint ramp: well kept, low contrast
    plane[8:, :8] = np.linspace(0, 255, 8)[None, :]  # a steep ramp: contrast, but 98.6% kept
    assert example.pick_block(plane) == (8, 8)


def test_the_checked_in_figure_is_a_png() -> None:
    if not FIGURE.exists():  # pragma: no cover - a distribution without doc/
        pytest.skip("figure missing")
    assert FIGURE.read_bytes()[:8] == PNG_MAGIC
